export { SplashScreen } from './Splash'
export { ProfilePage } from './Profile'
export { ProfessionalAreaPage } from './ProfessionalArea'
export { PatientsPage } from './Patients'
export { LoginPage } from './Login'
export { ProntuarioPage } from './Prontuario'
export { EvolucoesPendentesPage } from './Evolucoes'
export { RelatoriosPage } from './Relatorios'
export { AgendaPage } from './Agenda'
export { MinhasUnidadesPage } from './MinhasUnidades'
export { PacientesDaUnidadePage } from './PacientesDaUnidade'
export { EvolucoesDoPacientePage } from './EvolucoesDoPaciente'
export { PendenciasPage } from './Pendencias'
export { EvolucaoDetalhesPage } from './EvolucaoDetalhes'
export { SobrePage } from './Sobre'
export { FolhaRegistro as FolhaRegistroPage } from './FolhaRegistro'
export { FolhaRegistroEditor } from './FolhaRegistroEditor'
